import React, { useState } from 'react';
import { Eye, EyeOff, Facebook, Twitter, Instagram, Youtube } from 'lucide-react';

export default function LoginPage() {
  const [showPassword, setShowPassword] = useState(false);
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [rememberMe, setRememberMe] = useState(false);

  const handleSubmit = async () => {
    console.log('Login attempt:', { email, password, rememberMe });

    if (!email || !password) {
      alert("Please enter email and password");
      return;
    }

    try {
      const response = await fetch("http://localhost:5000/login", {
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          email,
          password
        })
      });

      let data;
      try {
        data = await response.json();
      } catch (e) {
        console.error("Error parsing response body:", e);
        alert("❌ Server sent an unreadable response.");
        return;
      }

      if (!response.ok) {
        const errorMessage = data.message || data.error || data.detail || "Login failed: Server Error (Check Console for details)";
        console.error(`Login Failed (Status ${response.status}):`, data);
        alert(`❌ Login Failed: ${errorMessage}`);
        return;
      }

      if (data.success || data.token) {
        alert("✅ Login Successful");
        console.log("User:", data.user);
        console.log("Token:", data.token);
        
        const storage = rememberMe ? localStorage : sessionStorage;
        storage.setItem('token', data.token);
        storage.setItem('user', JSON.stringify(data.user));
        
        // Navigate to home/dashboard - you'll need to implement this
        // navigate('/');
        
      } else {
        alert(data.message || "❌ Invalid Login: Response success field was false.");
      }

    } catch (error) {
      console.error("Network or Unexpected Error:", error);
      alert("❌ Could not connect to the server (Network or CORS issue).");
    }
  };

  return (
    <div className="login-container">
      {/* Background Video with Overlay */}
      <video
        className="background-video"
        autoPlay
        loop
        muted
        playsInline
      >
        <source src="/background.mp4" type="video/mp4" />
        Your browser does not support the video tag.
      </video>
      <div className="background-overlay"></div>

      {/* Content Container */}
      <div className="content-wrapper">
        
        {/* Left Side - Welcome Text */}
        <div className="welcome-section">
          <h1 className="welcome-title">
            Welcome<br />Back
          </h1>
          <p className="welcome-text">
            This is a subheading text where will be generated by the readable content of a page when looking at its layout. The point of using.
          </p>
          
          {/* Social Media Icons */}
          <div className="social-icons">
            <button className="social-button" type="button">
              <Facebook size={20} />
            </button>
            <button className="social-button" type="button">
              <Twitter size={20} />
            </button>
            <button className="social-button" type="button">
              <Instagram size={20} />
            </button>
            <button className="social-button" type="button">
              <Youtube size={20} />
            </button>
          </div>
        </div>

        {/* Right Side - Sign In Form */}
        <div className="form-container">
          <div className="form-card">
            <h2 className="form-title">Sign in</h2>
            
            <div className="form-fields">
              {/* Email Input */}
              <div className="input-group">
                <label className="input-label">
                  Email Address
                </label>
                <input
                  type="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  className="input-field"
                  placeholder="Enter your email"
                />
              </div>

              {/* Password Input */}
              <div className="input-group">
                <label className="input-label">
                  Password
                </label>
                <div className="password-wrapper">
                  <input
                    type={showPassword ? 'text' : 'password'}
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    className="input-field"
                    placeholder="Enter your password"
                  />
                  <button
                    onClick={() => setShowPassword(!showPassword)}
                    className="password-toggle"
                    type="button"
                  >
                    {showPassword ? <EyeOff size={20} /> : <Eye size={20} />}
                  </button>
                </div>
              </div>

              {/* Remember Me Checkbox */}
              <div className="remember-me">
                <input
                  type="checkbox"
                  id="remember"
                  checked={rememberMe}
                  onChange={(e) => setRememberMe(e.target.checked)}
                  className="checkbox"
                />
                <label htmlFor="remember" className="checkbox-label">
                  Remember Me
                </label>
              </div>

              {/* Sign In Button */}
              <button
                onClick={handleSubmit}
                className="submit-button"
                type="button"
              >
                Sign in now
              </button>

              {/* Lost Password Link */}
              <div className="forgot-password">
                <button className="link-button" type="button">
                  Lost your password?
                </button>
              </div>

              {/* Terms and Privacy */}
              <p className="terms-text">
                By clicking on 'Sign in now' you agree to{' '}
                <button className="link-inline" type="button">
                  Terms of Service
                </button>
                {' | '}
                <button className="link-inline" type="button">
                  Privacy Policy
                </button>
              </p>
            </div>
          </div>
        </div>
      </div>

      <style>{`
        * {
          margin: 0;
          padding: 0;
          box-sizing: border-box;
        }

        body {
          margin: 0;
          padding: 0;
          overflow-x: hidden;
        }

        .login-container {
          min-height: 100vh;
          width: 100%;
          display: flex;
          align-items: center;
          justify-content: center;
          position: relative;
          overflow: hidden;
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
        }

        /* Background Video */
        .background-video {
          position: absolute;
          top: 0;
          left: 0;
          width: 100%;
          height: 100%;
          object-fit: cover;
          z-index: 1;
        }

        .background-overlay {
          position: absolute;
          top: 0;
          right: 0;
          bottom: 0;
          left: 0;
          background: linear-gradient(to right, rgba(0, 0, 0, 0.75), rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.4));
        }

        .content-wrapper {
          position: relative;
          z-index: 10;
          width: 100%;
          max-width: 1400px;
          margin: 0 auto;
          padding: 2rem 2rem;
          display: flex;
          align-items: center;
          justify-content: space-between;
          gap: 4rem;
        }

        /* Left Side */
        .welcome-section {
          flex: 1;
          max-width: 600px;
          padding-right: 2rem;
          animation: fade-in 0.8s ease-out;
        }

        .welcome-title {
          font-size: 4.5rem;
          font-weight: 700;
          color: white;
          margin-bottom: 1.5rem;
          line-height: 1.1;
          letter-spacing: -0.02em;
        }

        .welcome-text {
          color: rgba(255, 255, 255, 0.85);
          font-size: 1.125rem;
          line-height: 1.7;
          margin-bottom: 2.5rem;
          max-width: 500px;
        }

        .social-icons {
          display: flex;
          gap: 1rem;
        }

        .social-button {
          width: 2.75rem;
          height: 2.75rem;
          border-radius: 50%;
          background-color: rgba(255, 255, 255, 0.1);
          backdrop-filter: blur(10px);
          display: flex;
          align-items: center;
          justify-content: center;
          color: white;
          border: 1px solid rgba(255, 255, 255, 0.15);
          cursor: pointer;
          transition: all 0.3s ease;
        }

        .social-button:hover {
          background-color: rgba(255, 255, 255, 0.2);
          transform: translateY(-3px);
          box-shadow: 0 5px 15px rgba(0, 0, 0, 0.3);
        }

        /* Right Side - Form */
        .form-container {
          width: 100%;
          max-width: 480px;
          flex-shrink: 0;
          animation: slide-in 0.8s ease-out;
        }

        .form-card {
          background-color: rgba(255, 255, 255, 0.12);
          backdrop-filter: blur(20px);
          -webkit-backdrop-filter: blur(20px);
          border-radius: 1.25rem;
          padding: 2.5rem;
          box-shadow: 0 20px 60px rgba(0, 0, 0, 0.4);
          border: 1px solid rgba(255, 255, 255, 0.18);
        }

        .form-title {
          font-size: 2rem;
          font-weight: 700;
          color: white;
          margin-bottom: 2rem;
        }

        .form-fields {
          display: flex;
          flex-direction: column;
          gap: 1.5rem;
        }

        .input-group {
          width: 100%;
        }

        .input-label {
          display: block;
          color: white;
          font-size: 0.9rem;
          font-weight: 500;
          margin-bottom: 0.6rem;
          letter-spacing: 0.01em;
        }

        .input-field {
          width: 100%;
          padding: 0.875rem 1rem;
          border-radius: 0.625rem;
          background-color: rgba(255, 255, 255, 0.95);
          color: #1f2937;
          border: none;
          outline: none;
          font-size: 1rem;
          transition: all 0.3s ease;
          font-family: inherit;
        }

        .input-field::placeholder {
          color: #9ca3af;
        }

        .input-field:focus {
          background-color: white;
          box-shadow: 0 0 0 3px rgba(249, 115, 22, 0.4);
        }

        .password-wrapper {
          position: relative;
        }

        .password-toggle {
          position: absolute;
          right: 1rem;
          top: 50%;
          transform: translateY(-50%);
          background: none;
          border: none;
          color: #6b7280;
          cursor: pointer;
          display: flex;
          align-items: center;
          justify-content: center;
          padding: 0.25rem;
          transition: color 0.2s ease;
        }

        .password-toggle:hover {
          color: #1f2937;
        }

        .remember-me {
          display: flex;
          align-items: center;
          gap: 0.5rem;
        }

        .checkbox {
          width: 1.125rem;
          height: 1.125rem;
          border-radius: 0.25rem;
          cursor: pointer;
          accent-color: #f97316;
        }

        .checkbox-label {
          color: white;
          font-size: 0.9rem;
          cursor: pointer;
          user-select: none;
        }

        .submit-button {
          width: 100%;
          padding: 0.875rem 1rem;
          border-radius: 0.625rem;
          background: linear-gradient(135deg, #f97316 0%, #ea580c 100%);
          color: white;
          font-weight: 600;
          border: none;
          cursor: pointer;
          font-size: 1rem;
          transition: all 0.3s ease;
          box-shadow: 0 4px 15px rgba(249, 115, 22, 0.4);
          margin-top: 0.5rem;
        }

        .submit-button:hover {
          background: linear-gradient(135deg, #ea580c 0%, #dc2626 100%);
          transform: translateY(-2px);
          box-shadow: 0 6px 20px rgba(249, 115, 22, 0.5);
        }

        .submit-button:active {
          transform: translateY(0);
        }

        .forgot-password {
          text-align: center;
        }

        .link-button {
          color: white;
          font-size: 0.9rem;
          background: none;
          border: none;
          cursor: pointer;
          transition: color 0.3s ease;
          text-decoration: none;
        }

        .link-button:hover {
          color: #fb923c;
        }

        .terms-text {
          text-align: center;
          color: rgba(255, 255, 255, 0.75);
          font-size: 0.8rem;
          line-height: 1.6;
        }

        .link-inline {
          color: white;
          background: none;
          border: none;
          cursor: pointer;
          text-decoration: underline;
          font-size: 0.8rem;
          transition: color 0.3s ease;
          padding: 0;
        }

        .link-inline:hover {
          color: #fb923c;
        }

        @keyframes fade-in {
          from {
            opacity: 0;
            transform: translateX(-30px);
          }
          to {
            opacity: 1;
            transform: translateX(0);
          }
        }

        @keyframes slide-in {
          from {
            opacity: 0;
            transform: translateX(30px);
          }
          to {
            opacity: 1;
            transform: translateX(0);
          }
        }

        /* Responsive Design */
        @media (max-width: 1200px) {
          .content-wrapper {
            gap: 3rem;
          }
          
          .welcome-title {
            font-size: 3.5rem;
          }
        }

        @media (max-width: 1024px) {
          .content-wrapper {
            flex-direction: column;
            text-align: center;
            padding: 3rem 2rem;
          }
          
          .welcome-section {
            padding-right: 0;
            margin-bottom: 2rem;
            max-width: 100%;
          }
          
          .welcome-title {
            font-size: 3rem;
          }
          
          .social-icons {
            justify-content: center;
          }

          .form-container {
            max-width: 500px;
          }
        }

        @media (max-width: 640px) {
          .welcome-title {
            font-size: 2.5rem;
          }
          
          .form-card {
            padding: 2rem 1.5rem;
          }
          
          .content-wrapper {
            padding: 2rem 1rem;
          }
        }
      `}</style>
    </div>
  );
}
